apiVersion: v1 
kind: ServiceAccount
metadata:
  name: server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role # <-- Caso a role seja para todo o cluster usar ClusterRole
metadata:
  name: server-read
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---
# Realiza o bind do ServiceAccount com a Role
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding # <-- Caso a role seja para todo o cluster usar ClusterRoleBinding
metadata:
  name: server-read-bind
subjects:
- kind: ServiceAccount
  name: server 
  namespace: prod
roleRef:
  kind: Role # <-- Caso a role seja para todo o cluster usar ClusterRole
  name: server-read
  apiGroup: rbac.authorization.k8s.io
